name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Test the Docker image
      run: docker build -t recipe-site --target test .
    - name: Build the Docker image
      run: docker build -t recipe-site .
    - name: Build and Push
      id: docker_build
      if: github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/recipesite:latest
    - name: Deploy
      id: deploy
      if: github.ref == 'refs/heads/main'
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'http://80.192.196.161:55555/update'
        method: 'POST'
        
